#!/bin/bash
if [[ $@ -le 1 ]];then
	echo "Use: $0 commit_msg"
fi
git add ./* && git add ./.* 
git commit -m "$1" 
eval $(ssh-agent)
ssh-add -D && eval ssh-add "$UBUNTU_CONFIG_KEY"
git push origin main 
ssh-add -D 
