#!/usr/bin/bash

# Not sure if that would would with hyprland config files as systemlinks

PTD="$PWD"

# link config files to main directory
create_sys_links() {
	local source="$1"
	local target="${2:-${path:-$HOME}}"
	ln -sf "$source" "$target"
}


for i in *;do
	
	case $i in 
		".") 
			continue
			;;
		"..")
			continue
			;;
		".setup.swp")
			continue
			;;
		"setup")
			continue
			;;
		"cfgs")
			if [[ ! -d "$HOME/.config/hypr/cfgs" ]];then
                                mkdir -p "$HOME/.config/hypr/cfgs"
			fi
			cd ./cfgs
			for b in *; do
				cp "$b" "$HOME/.config/hypr/cfgs" 
			done
			;;
		*)	
			cd "$PTD"		
			cp "$PWD/$i" "$HOME/.config/hypr"
			;;
	esac
done
