#!/usr/bin/bash
# to work properly

if ! command -v fd 2>&1 >/dev/null | command -v fzf 2>&1 >/dev/null; then
  echo "Needs fd and fzf to work" && exit 1
fi

#PATHS
gitconfig="$HOME/.config/git"

# link config files to main directory
create_sys_links() {
  local source="$1"
  local target="${2:-${path:-$HOME}}"
  ln -svf "$source" "$target"
}

#Select dir for gitconfig
select_dir() {
  selected_dir=$(fd --type d --hidden . / | fzf)

  ## path to cfgs
  ## /data/configs_and_scripts/config-user-related/gitconfig-files

  cfg_info=$(
    cat <<EOF
[includeIf "gitdir:${selected_dir}/"]
    path = "$HOME/.config/git/${i}"
EOF
  )

  cp "$HOME/.gitconfig" "$HOME/.old.gitconfig" >/dev/null 2>&1
  echo "$cfg_info" >>"$HOME/.gitconfig" && echo "$i added to .gitconfig"
}

for i in .* *; do
  case "$i" in
  "." | ".." | ".setup.swp" | "setup" | "files" | "export_extra_path")
    continue
    ;;

  ".gitconfig")
    create_sys_links "$PWD/${i}" "$HOME/${i}"
    ;;

  ".gitconfig-"*)
    if [[ ! -d "$gitconfig" ]]; then
      mkdir -p "$gitconfig"
    fi
    if [[ -L "$gitconfig/${i}" ]]; then
      echo "$i exists" && continue
    else
      echo "Add ${i} into ${gitconfig}/${i} ?"
      select an in yes no; do
        if [[ "$an" == "yes" ]]; then
          echo "select path for repo ${i}... press enter to continue"
          read forget
          select_dir "$i"
          create_sys_links "$PWD/$i" "${gitconfig}/${i}"
          break
        elif [[ "$an" == "no" ]]; then
          break
        fi
      done
    fi
    ;;
  "tmux.conf")
    echo "transfer tmux.conf to its config?"
    select an in yes no; do 
      if [[ "$an" == "yes" ]];then
        if [[ -d "$HOME/.config/tmux" ]]; then
          create_sys_links "$PWD/$i" "$HOME/.config/tmux/$i"
        else 
          echo "tmux dir doesnt exists"
        fi
      elif [[ "$an" == "no" ]];then
        break
      fi
    done

  *)
    #create_sys_links "$PWD/$i" "${path:-$HOME}"
    continue
    ;;
  esac
done
