#!/usr/bin/bash

# link config files to main directory
create_sys_links() {
	local source="$1"
	local target="${2:-${path:-$HOME}}"
	ln -sf "$source" "$target"
}


for i in .*;do
	
	case $i in 
		".") 
			continue
			;;
		"..")
			continue
			;;
		".setup.swp")
			continue
			;;
		".gitconfig-configs"|".gitconfig-lab")
			if [[ ! -d ~/.config/git ]];then
			     mkdir -p ~/.config/git
			fi
			create_sys_links "$PWD/$i" "${path:-$HOME}/.config/git"
			;;
		"export_extra_path")
			continue
			;;
		"kitty.conf")
i			[[ ! -d ~/.config/kitty ]] && mkdir -p ~/.config/kitty
			create_sys_links "$PWD/$i" "${path:-$HOME}/.config/kitty"
			cp "$PWD/files/kitty/background.jpg" "${path:-$HOME}/.config/kitty"
			;;
		*)
			create_sys_links "$PWD/$i" "${path:-$HOME}"
			;;
	esac
done
