set -g mode-keys vi
set -g update-environment "WAYLAND_DISPLAY DISPLAY HYPRLAND_INSTANCE_SIGNATURE KITTY_LISTEN_ON"
bind-key -T copy-mode-vi K send-keys -X page-up
bind-key -T copy-mode-vi J send-keys -X page-down

set -g pane-active-border-style fg=blue
# Show arrows pointing directly to the active pane (Requires tmux 3.3+)
set -g pane-border-indicators both
set -g pane-border-lines heavy


# allow for shared clipboard with my containers
set -g allow-passthrough on
set -g set-clipboard external

# to refer to tmux variables
# tmux display-message -p '#{config_files}'
# -p to send output to stdout
