#!/usr/bin/bash

# link config files to main directory

create_sys_links() {
	ln -sf "$1" ~/
}

for i in .*;do
	list+=("$i")
done
for i in "${list[@]}";do
	
	# Option a with if statments
	#if [[ $i == '.' || $i == '..' || $i == '.setup.swp' ]];then
	#	continue
	#fi
	# option b with case
	case $i in 
		".") 
			continue
			;;
		"..")
			continue
			;;
		".setup.swp")
			continue
			;;
		*)
			create_sys_links "$PWD/$i"
	esac
done
