#!/bin/bash

TEXT="$(wl-paste -p)"
if [[ -z "$TEXT" ]];then
	notify-send "Something wrong with translator output"
	exit 1
fi
translation=$(/home/Filip/.local/bin/translator "$TEXT")
notify-send -t 10000 "$translation"
~/.local/bin/adding-english "$TEXT" "$translation"

