#!/bin/bash
TEXT="$(wl-paste -p)"
if [[ -z "$TEXT" ]];then
	notify-send "No text selected" 
	exit 1
fi
translation=$(/home/Filip/.local/bin/translator "$TEXT")
notify-send -t 10000 "$translation"
~/.local/bin/adding-english "$TEXT" "$translation"

