#!/usr/bin/bash

# link config files to main directory

if [[ -d ~/.local/bin ]];then 
	echo ".local/bin is there"
else
	mkdir -p "$HOME/.local/bin"
fi

create_sys_links() {
        ln -sf "$1" ~/.local/bin
}

for i in *;do
	list+=("$i")
done

for i in "${list[@]}";do
	
	# Option a with if statments
	#if [[ $i == '.' || $i == '..' || $i == '.setup.swp' ]];then
	#	continue
	#fi
	# option b with case
	case $i in 
		setup) 
			continue
			;;
		*)
			create_sys_links "$PWD/$i" 
	esac
done
