#!/bin/bash

if [[ "$#" -ne 1 ]]; then
  echo "Use: $0 word / sentence to translate"
fi

# ~/.config/hypr/cfgs/keybindings // bind into SUPER + Z /home/Filip/.local/bin/deepl_translate" -> goes into anki as well

eval $(grep "API_KEY_DEEPL" "$HOME/.bashrc_local")
export API_KEY_DEEPL

#API_KEY_DEEPL="hidden in local_rc"
ENDPOINT="https://api-free.deepl.com/v2/translate"
TEXT=$1

RESPONSE=$(curl -s -X POST "$ENDPOINT" \
  --header "Authorization: DeepL-Auth-Key $API_KEY_DEEPL" \
  --header "Content-Type: application/json" \
  --data "{ \"text\": [\"${TEXT}\"], \"target_lang\": \"PL\"}")

echo $RESPONSE | jq '.translations[] | .text' | sed 's|^"||;s|"$||'
